config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :runscope_tests

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/runscope_test.rb
class RunscopeTest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  session[:previous_url] || "/runscope_tests"
end


  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/runscope_tests_controller.rb
class RunscopeTestsController < ApplicationController
  before_action :set_runscope_test, only: [:show, :edit, :update, :destroy]

  # GET /runscope_tests
  # GET /runscope_tests.json
  def index
    @runscope_tests = RunscopeTest.all
  end

  # GET /runscope_tests/1
  # GET /runscope_tests/1.json
  def show
  end

  # GET /runscope_tests/new
  def new
    @runscope_test = RunscopeTest.new
  end

  # GET /runscope_tests/1/edit
  def edit
  end

  # POST /runscope_tests
  # POST /runscope_tests.json
  def create
    @runscope_test = RunscopeTest.new(runscope_test_params)

    respond_to do |format|
      if @runscope_test.save
        format.html { redirect_to @runscope_test, notice: 'Runscope test was successfully created.' }
        format.json { render :show, status: :created, location: @runscope_test }
      else
        format.html { render :new }
        format.json { render json: @runscope_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runscope_tests/1
  # PATCH/PUT /runscope_tests/1.json
  def update
    respond_to do |format|
      if @runscope_test.update(runscope_test_params)
        format.html { redirect_to @runscope_test, notice: 'Runscope test was successfully updated.' }
        format.json { render :show, status: :ok, location: @runscope_test }
      else
        format.html { render :edit }
        format.json { render json: @runscope_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runscope_tests/1
  # DELETE /runscope_tests/1.json
  def destroy
    @runscope_test.destroy
    respond_to do |format|
      format.html { redirect_to runscope_tests_url, notice: 'Runscope test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runscope_test
      @runscope_test = RunscopeTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runscope_test_params
      params.require(:runscope_test).permit(:name, :url)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/runscope_tests_helper.rb
module RunscopeTestsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "SCARFACE", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<img style="float: left;" src="http://laguestlist.com/wp-content/uploads/2015/08/scarfacea_a_l.jpg" height="250" width="250" hspace="30">
<h1>WELCOME TO SCARFACE</h1>
<h2>Login to kick off RunScope tests</h2>
<p>Click "Sign Up" if you dont already have an account</p>
<div>"Say hello to my little friend"</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scarface</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/runscope_tests/_form.html.erb
<%= form_for @runscope_test, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :url, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  runscope_tests_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/runscope_tests/edit.html.erb
<%- model_class = RunscopeTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => RunscopeTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runscope_tests/index.html.erb
<%- model_class = RunscopeTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => RunscopeTest %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @runscope_tests.each do |runscope_test| %>
      <tr>
        <td><%= runscope_test.id %></td>
        <td><%= runscope_test.name %></td>
        <td><%= link_to  runscope_test.url, runscope_test.url, :target => '_blank' %></td>
        <td><%=l runscope_test.created_at, format: :long %></td>
        <td><button type="button" ><%= link_to 'TEST', runscope_test.url, :target => '_blank' %></button></td>
        <td>
          <%= link_to runscope_test_path(runscope_test), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <!--<%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>-->
            <button type="button">View</button>
          <%- end -%>
          <%= link_to runscope_test_path(runscope_test), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <!--<%= glyph 'remove' %> -->
            <button type="button">Delete</button>
            <td><button type="button", action="/request" method="GET" ><%= link_to 'Results', runscope_test.url, :target => '_blank' %></button></td>

          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_runscope_test_path,
            :class => 'btn btn-primary' %>

app/views/runscope_tests/new.html.erb
<%- model_class = RunscopeTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => RunscopeTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/runscope_tests/show.html.erb
<%- model_class = RunscopeTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => RunscopeTest %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @runscope_test.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:url) %></dt>
      <dd><pre class="prettyprint"><%= @runscope_test.url %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              runscope_tests_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_runscope_test_path(@runscope_test), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              runscope_test_path(@runscope_test),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>